README: trivial fixes
let-def/migrate-parsetree pull request #64
Opened 2019-01-17 18:19 UTC by Armael

2019-01-17 18:24 UTC, ghost requested changes

2019-01-17 18:24 UTC, ghost commented on README.md
> +Try `opam install cinaps`.
```suggestion
You can install it via opam: `opam install cinaps`.
```

2019-01-17 22:17 UTC, Armael commented on README.md
> +Try `opam install cinaps`.
Thanks!

2019-01-21 19:19 UTC, merged

2019-01-21 19:19 UTC, diml commented
Thanks!